### ISSUE TITLE
Update Data availability page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#196]
- [x] Add list of which database links require holding for publication and which we can proceed with (e.g. Dryad, OSF etc)
- [x] Edit pink type links to embedded links
- [x] Fix schematron messages for tags that didn't convert properly on import
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page
- [ ] Share page with Exeter if relevant

### Definition of done
- [ ] Team reviewed and approved page?
- [ ] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife, @naushinthomson, @griffithsc  - the main update here is now ready for review: https://elifeproduction.slab.com/posts/data-availability-qi8vg0qp#huuz0-database-publication-policies

It's not a complete list because I can't get to data release policies for all the databases, but I've included as many as I could find.
