### ISSUE TITLE
Update Data availability page after PRC

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#215]
- [x] Add updates to page to indicate that authors now control when Dryad datasets are released
- [x] Fred approved page
- [x] James approved page
- [ ] Naushin approved page
- [x] Rebecca approved page
- [ ] Share page with Exeter if relevant

### Definition of done
- [ ] Team reviewed and approved page?
- [ ] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by JGilbert-eLife** [comment]
@fred-atherden @naushinthomson @rkcook312 -- I have updated this page to remove any mention of Dryad being a special case. Since it is now entirely under the authors' control, I don't think we need to make any distinction for it: https://elifeproduction.slab.com/posts/data-availability-qi8vg0qp#hxyvh-data-that-is-not-yet-public

Does that seem OK to you?

**Comment by fred-atherden** [comment]
LGTM - thanks!

**Comment by rkcook312** [comment]
Looks good to me, thanks!
